image: node:9.11.1

# cache node_modules between all jobs
cache:
  paths:
    - node_modules/

# run jest tests in the pipeline
test:
  stage: test
  script:
    - npm install
    - npm run test-code
  only:
    - merge_requests

# deploy documentation when master (stable) gets updated to gitlab pages
pages:
  script:
    - npm install
    - npm run build-styleguide
  artifacts:
    paths:
      - public
  only:
    - master

publish:
  stage: deploy
  only:
    - tags
  script:
    - echo "">>.npmrc
    - echo "@find-package:registry=https://gitlab.l.invia.lan/api/v4/packages/npm/">>~/.npmrc
    - echo "//gitlab.l.invia.lan/api/v4/packages/npm/:_authToken=${GITLAB_NPM_TOKEN}">>~/.npmrc
    - echo "//gitlab.l.invia.lan/api/v4/projects/418/packages/npm/:_authToken=${GITLAB_NPM_TOKEN}">>~/.npmrc
    - echo "strict-ssl=false">>~/.npmrc
    - npm publish
